name: Publish Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
          pip install -e .

      - name: Run Tests
        run: pytest tests/

  deploy:
    name: Deploy to PyPI
    needs: test  # Only runs if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Inject Version into Files
        run: |
          sed -i "s/version = .*/version = \"$VERSION\"/" pyproject.toml
          sed -i "s/version = .*/version = $VERSION/" setup.cfg
          sed -i "s/version=.*/version=\"$VERSION\",/" setup.py

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch --prune --unshallow

          DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')

          git checkout $DEFAULT_BRANCH
          git pull origin $DEFAULT_BRANCH
          git commit -am "Set version to $VERSION"
          
      - name: Push Version Update
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin $DEFAULT_BRANCH

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install build twine

      - name: Build Package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      - name: Notify GitHub of Deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/deployments \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -d '{
            "ref": "'"${GITHUB_REF}"'",
            "auto_merge": false,
            "required_contexts": [],
            "environment": "PyPI",
            "description": "Deployed version '${{ env.VERSION }}' to PyPI",
            "transient_environment": false
          }'